### ISSUE TITLE
IdempotentLowering and ghc 9.2

### ISSUE THREAD

**Issue by adamConnerSax** [polysemy-research/polysemy-zoo#74]
polysemy-zoo (hackage latest and d1564f04a2089472a22104f9ecce94674a56ef77) fails to compile on ghc9.2.2 because of errors in IdempotentLowering.hs. The first:
```haskell
src/Polysemy/IdempotentLowering.hs:26:16: error:
    • Couldn't match representation of type: forall x1. m1 x1 -> n1 x1
                               with that of: m x -> n x
        arising from a use of ‘coerce’
    • In the first argument of ‘($)’, namely ‘coerce’
      In the second argument of ‘($)’, namely ‘coerce $ Nat f’
      In the expression: pure $ coerce $ Nat f
    • Relevant bindings include
        f :: forall (x :: k). m x -> n x
          (bound at src/Polysemy/IdempotentLowering.hs:26:5)
        nat :: (forall (x :: k). m x -> n x)
               -> base (forall (x :: k). m x -> n x)
          (bound at src/Polysemy/IdempotentLowering.hs:26:1)
   |
26 | nat f = pure $ coerce $ Nat f
   |                ^^^^^^
```

I took a shot at figuring this out, googled a bit. etc. but I got nowhere.

**Comment by KingoftheHomeless** [comment]
`IdempotentLowering` is old, unreliable, outclassed by `Final`, and deprecated. I suggest removing the module altogether.
This makes for a good first issue!

**Comment by ShapeOfMatter** [comment]
To clarify; this issue is resolved, yes?

**Comment by KingoftheHomeless** [comment]
Yup; merged and released.
